### ISSUE TITLE
Broker Roadmap

### ISSUE THREAD

**Issue by SrGaabriel** [LorittaBot/Loritta#2181]
📦 Things that we can do:

- [x] 📊 Backups system;
- [x] 🛰️ Create an own application to connect in the stocks API;
- [x] 🔔 Disable +broker command if there wasn't a update received recently;
- [x] ⭕ Disable buying/selling inactive stocks;
- [ ] 📝 More pages in +transactions & if the transaction was a bet, show both participants;
- [ ] ⏰ `+pay` command delay;
- [x] 📈 Add a global transaction log with webhooks;
- [x] 🚀 Add a killswitch to disable all `addSonhos` and `takeSonhos` calls;
- [x] 💡 Require both participants of a `+pay` transaction to accept it;

**Comment by xGabrielDEV** [comment]
About the +pay command, we could require the user that is going to receive the dreams to accept the transaction, it'll avoid people giving dreams to random people/bots.

**Comment by MrPowerGamerBR** [comment]
2 and 3 are implemented, if the plugin haven't received a ping in the last 15s or if the plugin haven't received a stock update in the last 60s, all actions are rejected. https://github.com/LorittaBot/Loritta/commit/f45655d8b8eca3ca336a203ce41a2d013d86f515

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/Loritta/commit/daae84b17a6bcb5a8cf6a6dc08af2990d98cd2a8

**Comment by MrPowerGamerBR** [comment]
While not related to a dupe bug, it would be nice to change the `insert` to a `batchInsert` to make `+broker buy` more faster.

**Comment by SrGaabriel** [comment]
I'll close this issue since there's no need to implement the remaining items.
